# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dmem_lib/dmem_lib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmem_lib || ORIG_REF_NAME==dmem_lib} -quiet] -quiet

# IP: ip/imem_lib/imem_lib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imem_lib || ORIG_REF_NAME==imem_lib} -quiet] -quiet

# XDC: ip/dmem_lib/dmem_lib_ooc.xdc

# XDC: ip/imem_lib/imem_lib_ooc.xdc
